### ISSUE TITLE
zod-nestjs - Circular dependency error for object that contains a union

### ISSUE THREAD

**Issue by nat-e** [anatine/zod-plugins#158]
I am using `@anatine/zod-nestjs` 2.0.3 and I have an issue when I try to generate the swagger doc for an object that contains a union.

A minimal reproduction can be achieved when adding this decorator to any route:
```typescript
@ApiBody({
  type: createZodDto(z.object({xxx: z.union([z.string(), z.number()])})),
})
```

Note that if the union is at the top level, I have no issue:
```typescript
@ApiBody({
  type: createZodDto(z.union([z.string(), z.number()])),
})
```

I get the following error:

```
Error: A circular dependency has been detected (property key: "xxx"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
at SchemaObjectFactory.createNotBuiltInTypeReference (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:204:19)
at SchemaObjectFactory.createSchemaMetadata (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:341:25)
at SchemaObjectFactory.mergePropertyWithMetadata (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:146:21)
at /usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:103:35
at Array.map (<anonymous>)
at SchemaObjectFactory.extractPropertiesFromType (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:102:52)
at SchemaObjectFactory.exploreModelSchema (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:116:41)
at /usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:33:36
at Array.map (<anonymous>)
at SchemaObjectFactory.createFromModel (/usr/src/app/node_modules/.pnpm/@nestjs+swagger@7.1.1_@nestjs+common@10.0.4_@nestjs+core@10.0.4_class-transformer@0.5.1_class_dlldepy56kux6aiezqr2ipjcl4/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:20:45)
```

Thanks

**Comment by lcnlvrz-revelacion** [comment]
A workaround for this is just to use `generateSchema` from `@anatine/zod-openapi` directly in @ApiBody: 

```ts
@ApiBody({
    schema: generateSchema(yourZodSchema) as any,
  })
```
